#pragma config(Sensor, in1,    autonPot,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, shooterEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           liftMotor1,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightFrontMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftFrontMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           shooterMotor4, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           shooterMotor3, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           shooterMotor1, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           shooterMotor2, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftBackMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightBackMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          liftMotor2,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Utils.h"
#include "DriveSystem.h"
#include "Shooter.h"
#include "Lift.h"
//#include "Debug.h"
#include "Control.h"

/************************************************/

task main()
{
	startTask(driveSystem, kDefaultTaskPriority);
	startTask(shooter, kDefaultTaskPriority);
	startTask(lift, kDefaultTaskPriority);
	//startTask(debug, kDefaultTaskPriority);
	startTask(control, kDefaultTaskPriority);

	// BAD HACK. FIX ASAP.
	while (true) {}
}
